language: ruby

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server

rvm:
  - 2.2.5

bundler_args: --without development --deployment --jobs=3 --retry=3

cache: bundler

before_script:
  - psql -c 'create database wechat_starter_test;' -U postgres
  - bundle exec rake db:migrate --trace

script: bundle exec rake
