default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_authentication_development

test:
  <<: *default
  database: rails_authentication_test

production:
  <<: *default
  database: rails_authentication_production
